# Generated by Django 6.0.3 on 2026-04-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="expenses",
                to="wallets.wallet",
            ),
        ),
    ]
