# Generated by Django 6.0.3 on 2026-04-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="type",
            field=models.CharField(
                choices=[("expense", "Expense"), ("refund", "Refund")],
                default="expense",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["date"], name="expenses_ex_date_17a2b2_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category"], name="expenses_ex_categor_20264a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["wallet"], name="expenses_ex_wallet__5addb7_idx"
            ),
        ),
    ]
