# Generated by Django 6.0.3 on 2026-04-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expense_type_expense_expenses_ex_date_17a2b2_idx_and_more"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="vendors.vendor",
            ),
        ),
    ]
