# Generated by Django 6.0.3 on 2026-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expense_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_system_generated",
            field=models.BooleanField(default=False),
        ),
    ]
