# Generated by Django 6.0.3 on 2026-04-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_expense_is_system_generated"),
        ("wallets", "0002_alter_wallettransaction_expense_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpensePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="expenses.expense",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wallets.wallet",
                    ),
                ),
            ],
        ),
    ]
