# Generated by Django 6.0.3 on 2026-04-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_expenseitem"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="expenseitem",
            new_name="expenses_ex_expense_8267e5_idx",
            old_name="expenses_ex_expense_0d2c3c_idx",
        ),
    ]
