# Generated by Django 6.0.3 on 2026-04-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "expenses",
            "0008_rename_expenses_ex_expense_0d2c3c_idx_expenses_ex_expense_8267e5_idx",
        ),
        ("wallets", "0002_alter_wallettransaction_expense_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ContractorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("phase", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="contractors.contractor",
                    ),
                ),
                (
                    "linked_expense",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expenses.expense",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wallets.wallet"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="contractors_date_e76495_idx"),
                    models.Index(
                        fields=["contractor"], name="contractors_contrac_2a91e0_idx"
                    ),
                ],
            },
        ),
    ]
