# Generated by Django 6.0.3 on 2026-04-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0005_expense_is_system_generated"),
        ("wallets", "0002_alter_wallettransaction_expense_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("default_wage", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("workers_count", models.PositiveIntegerField()),
                ("custom_work_note", models.CharField(blank=True, max_length=255)),
                (
                    "wage_per_worker",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_half_day", models.BooleanField(default=False)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("phase", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_expense",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expenses.expense",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wallets.wallet"
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.worktype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="attendance__date_61f2e1_idx")
                ],
            },
        ),
    ]
